pipeline {
    agent any
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'maven:3.9.0'
                    args '-v /root/.m2:/root/.m2'
                }
            }
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            agent {
                docker {
                    image 'maven:3.9.0'
                    args '-v /root/.m2:/root/.m2'
                }
            }
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
                success {
                    sh './jenkins/scripts/deliver.sh'
                }
            }
        }
        stage('Deploy') { 
            steps {
                script {
                    def jarFiles = findFiles(glob: "./target/**/*jar")
                    if (!jarFiles.isEmpty()) {
                        def firstJarFile = jarFiles[0]
                        echo "First JAR file found: ${firstJarFile.name}"
                        sshagent(credentials: ['ec2-user']) {
                            sh 'scp -o StrictHostKeyChecking=no -r ./target/${firstJarFile} ec2-user@3.89.182.48:/home/ec2-user'
                            sh 'ssh -o StrictHostKeyChecking=no ec2-user@3.89.182.48 java -jar /home/ec2-user/${firstJarFile}'
                            sleep(time: 1, unit: 'MINUTES')
                        }
                    } else {
                        echo "No JAR files found in the specified directory."
                    }
                }
            }
        }
    }
}
