pipeline {
    agent {
        docker {
            image 'maven:3.9.0'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deploy') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                script {
                    def filename = env.NAME + "-" + env.VERSION + ".jar"
                    node('any') {
                        sshagent(credentials: ['ec2-user']) {
                            sh 'ssh -o StrictHostKeyChecking=no ${SSH_CREDENTIALS} target/${fileName} ec2-user@ec2-3-89-182-48.compute-1.amazonaws.com:/home/ec2-user'
                            sh "ssh -o StrictHostKeyChecking=no ec2-user@ec2-3-89-182-48.compute-1.amazonaws.com java -jar /home/ec2-user/${fileName}"
                            sleep(time: 1, unit: 'MINUTES')
                        }
                    }
                }
            }
        }
    }
}
